### ISSUE TITLE
Group Project React-Redux - Setup Kanban Board

### ISSUE THREAD

**Issue by gak92** [gak92/space-travel-hub#21]
In this group project:

- We are 2 members:
     1- Ghazanfar Ali
     2- Mohamed Aachour
- We have assigned the task to each member except for the task for the 3rd member of the team.
- https://github.com/gak92/space-travel-hub/projects/1

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @gak92 & @AACHOURMOHAMED , This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed
- You can start with your project

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gak92** [comment]
@sja-thedude
Thanks for the feedback and approval
